### PR TITLE
Delegate to `Chars` and `CharIndices`

### LINKED ISSUE #3: Consider delegating to Chars/CharIndices instead of re-implementing logic
I noticed that structs in this crate doesn't fully implement the things supported by `Chars` and `CharIndices`, such as `DoubleEndedIterator` and `FusedIterator` (relatively recent addition). It is also missing the optional methods in `Iterator` (such as `count` and `size_hint`) which results in suboptimal performance.

I also noticed that this crate somewhat re-implements the logic of `Chars` and `CharIndices`. Notably, I believe the implementation of `as_str` is wrong, since it's supposed to return the remaining substring rather than the whole string ([demo](http://play.rust-lang.org/?gist=8fc734c5df7832a3fdfcf8f80f3425f7&version=stable&mode=debug)).

Would you be interested in switching to an implementation strategy that delegates to the built-in implementations? That was, we "more or less" don't have to worry about testing for correctness (other than the methods exists and takes the same arguments) since they are just forwarding to the underlying stdlib code.

Concretely, it would look something like this:

```rust
use std::str::{Chars, CharIndices};
use std::mem::{transmute, uninitialized};
use std::iter::{Iterator, DoubleEndedIterator, FusedIterator};

#[derive(Clone, Debug)]
struct OwnedChars {
    // This is needed to keep the actual buffer alive, but this should be
    // treated as opaque/read-only. Mutating this will invalidate the
    // iteratior and cause safety issues.
    storage: String,

    // Store and delegate all methods to this underlying iterator.
    // 'static is a lie, it really is 'self, but this is a private field and
    // we are exposing only safe APIs with the correct lifetime.
    delegate: Chars<'static>
}

pub trait IntoChars {
    fn into_chars(self) -> OwnedChars;
}

impl IntoChars for String {
     fn into_chars(self) -> OwnedChars {
        // First, move ourself into the owner
        let mut owner = OwnedChars {
            storage: self,
            delegate: unsafe { uninitialized() }
        };

        // Then, we can call .chars, which with have the same lifetime
        // of the owner. We need the transmute to "widen" the lifetime
        // into 'static which would allow us to store it in the owner.
        owner.delegate = unsafe { transmute(owner.storage.chars()) };

        owner
     }
}

// Now, we can just delegate everything to the underlying iterator...

impl OwnedChars {
    #[inline]
    fn as_str(&self) -> &str {
        self.delegate.as_str()
    }
}

impl Iterator for OwnedChars {
    type Item = char;

    #[inline]
    fn next(&mut self) -> Option<char> {
        self.delegate.next()
    }

    #[inline]
    fn count(self) -> usize {
        self.delegate.count()
    }

    #[inline]
    fn size_hint(&self) -> (usize, Option<usize>) {
        self.delegate.size_hint()
    }

    #[inline]
    fn last(self) -> Option<char> {
        self.delegate.last()
    }
}

impl DoubleEndedIterator for OwnedChars {
    #[inline]
    fn next_back(&mut self) -> Option<char> {
        self.delegate.next_back()
    }
}

impl FusedIterator for OwnedChars {}
```

Here is a [working version](https://play.rust-lang.org/?gist=838003b3424fc157da2d44f117c433c7&version=stable&mode=debug). (I got tired of writing the delegating code so I turned it into a macro, but that we can extract and maintain as a separate crate, with its own test.)

Thoughts?

### PR DESCRIPTION
**Pull request by chancancode**
Closes #3

I did end up making a `delegate` create, so I figured I would put this together quickly to see how it feels in real code. Unfortunately, as @doomrobo pointed out in #2, there isn't a good way to implement `clone` since the state/pointers are not managed by us anymore.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -14,75 +21,88 @@ pub trait OwnedCharsExt {
...
-    ($s:ident) => {
-        impl $s {
+    ($struct:ident, $method: ident, $item: ty) => {
+        impl $struct {
+            /// Create Self from a String, moving the String into Self
+            fn from_string(s: String) -> Self {
+                // First, move the string
+                let mut owned = $struct {
+                    s: s,
+                    i: unsafe { uninitialized() }
```
Comment (durka) [inline src/lib.rs]: My personal "unsafe code policy" is that when leaving an `unsafe` block, the invariants that we are screwing with should be restored. So could you just merge these two blocks so that lines 52-60 are under one `unsafe`?

File: src/lib.rs [hunk 2]
```diff
@@ -14,75 +21,88 @@ pub trait OwnedCharsExt {
...
+                };
+
+                // Then, we can call .chars, which with have the same lifetime
+                // of the owner. We need the transmute to "widen" the lifetime
+                // into 'static which would allow us to store it in the owner.
+                owned.i = unsafe { transmute(owned.s.$method()) };
```
Comment (durka) [inline src/lib.rs]: I'd prefer to write it as `transmute::<Chars, Chars<'static>(...)` just to be explicit that it's only changing the lifetime, but that'd require an extra parameter to the macro...

**Review by durka — APPROVED** [review]

**Comment by durka** [comment]
Looks great! Happy to be an early adopter of your macro :)

I meant to respond to your original issue, sorry for dropping that ball. If you can make that small change to the unsafe code I'll merge!

**Comment by chancancode** [comment]
Fixed!

**Comment by durka** [comment]
Awesome. I'll publish a new version soon, I guess it ought to be a minor version due to the `as_str` behavior fix. Since this is a fairly significant overhaul (given that it's a tiny crate!), would you like to be listed as one of the crate authors?

**Comment by chancancode** [comment]
Don’t worry about it! We should probably work on RFC-ing this into stdlib though 😄

**Comment by durka** [comment]
Yeah, I'm not sure about the struct names but it seems like a pretty small
RFC.

**Comment by durka** [comment]
Hello from the future... I was a Rust novice at the time, and didn't realize until two years later when nightly started complaining about `mem::uninitialized` that this trivially allows UB in safe code -- see #7.
